# -*- mode: python; -*-
# waf configuration file .waf --help pour commande par défaut
# ******************************************************************** CMD build
def build( bld ):
    print('→ build from ' + bld.path.abspath())
    # bld.program( source='xp-000-mg.cpp',
    # 		 target='xp-000-mg',
    # 		 includes=['.', '../include', '../src', '../src/pomdp'],
    # 		 use='JSON' )
    bld.program( source=['xp-001-pomdp.cpp'],
    		 target='xp-001-pomdp',
		 includes=['.', '../include', '../src'],
		 use=['JSON', 'GSL', 'BOOST'] )
    bld.program( source=['xp-002-cheesemaze.cpp'],
    		 target='xp-002-cheese',
		 includes=['.', '../include', '../src'],
		 use=['JSON', 'GSL', 'BOOST'] )
    bld.program( source=['xp-003-hmm.cpp'],
    		 target='xp-003-hmm',
		 includes=['.', '../include', '../src','../src/supelec'],
		 use=['JSON', 'GSL', 'BOOST', 'FTGL', 'GL', 'GLFW3'] )
    bld.program( source=['xp-004-rdsom.cpp'],
    		 target='xp-004-rdsom',
		 includes=['.', '../include', '../src','../src/supelec'],
		 use=['JSON', 'GSL', 'BOOST', 'FTGL', 'GLEW', 'GLFW3','EIGEN3', 'PNG','PNGWRITER'] )
    
