#!/usr/bin/env python
# encoding: utf-8

import os

def build(bld):
    print('→ build from ' + bld.path.abspath())
    
    # detect files that should be build : *.cpp not starting with '.' or '#'
    for file in os.listdir( bld.path.abspath() ):
        if file.endswith(".cpp") and not file.startswith( ('.','#')):
            # print(" _should build "+file[:-4])
            bld.program(
                source=[file],
                target = file[:-4],
                includes=['.', '../../include', '../../src'],
                use = ['FTGL','GLEW','GLFW3','PNG',
                       'PNGWRITER','ANTTWEAKBAR']
            )

